title: Taimoor Khan
logo: https://github.com/taimoorkhan-nlp/taimoorkhan-nlp.github.io/blob/main/Taimoor.jpg
description: Senior Researcher (ML, NLP and BigData)
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
